pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'simranmehta26/practice-11'
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/simranmehta26/practice-11.git', branch: 'main'
            }
        }

        stage('Build Java Application') {
            steps {
                dir('practice-11') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t simranmehta26/practice-11:latest -f practice-11/Dockerfile ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'simranmehta26', passwordVariable: 'simran.docker')]) {
                        sh "echo simran.docker | docker login -u simranmehta26 --password-stdin"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push simranmehta26/practice-11:latest"
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker rmi simranmehta26/practice-11:latest || true'
            }
        }
    }
}
